### ISSUE TITLE
Fails to initilize

### ISSUE THREAD

**Issue by mzch** [DocMarty84/koozic#44]
I tried to run postgresql and koozic separately and exec init commands as below:
```
#! /bin/sh

LOGLEVEL=debug

HOME=/srv/koozic
cd $HOME

OPTS=
OPTS=$OPTS" --pidfile=$HOME/run/koozic.pid"
OPTS=$OPTS" --without-demo=all"
OPTS=$OPTS" --init=all"
OPTS=$OPTS" --logfile="$HOME"/logs/koozic.log"
OPTS=$OPTS" --log-level="$LOGLEVEL
OPTS=$OPTS" -d koozic"
OPTS=$OPTS" --db_user=koozic"
OPTs=$OPTS" --db_password=password"
OPTS=$OPTS" --db_host=192.168.207.11"
OPTS=$OPTS" --db_port=5432"
OPTS=$OPTS" --db_sslmode=disable"
OPTS=$OPTS" --db_maxconn=10"
OPTS=$OPTS" --stop-after-init"

cd koozic
exec ./odoo-bin $OPTS
```

then an error occurred.
```
Traceback (most recent call last):
  File "./odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/srv/koozic/koozic-v3.0.0/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/srv/koozic/koozic-v3.0.0/odoo/cli/server.py", line 178, in run
    main(args)
  File "/srv/koozic/koozic-v3.0.0/odoo/cli/server.py", line 142, in main
    odoo.service.db._create_empty_database(db_name)
  File "/srv/koozic/koozic-v3.0.0/odoo/service/db.py", line 98, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/srv/koozic/koozic-v3.0.0/odoo/sql_db.py", line 649, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/srv/koozic/koozic-v3.0.0/odoo/sql_db.py", line 186, in __init__
    self._cnx = pool.borrow(dsn)
  File "/srv/koozic/koozic-v3.0.0/odoo/sql_db.py", line 532, in _locked
    return fun(self, *args, **kwargs)
  File "/srv/koozic/koozic-v3.0.0/odoo/sql_db.py", line 600, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```

How can I fix this issue?

**Comment by DocMarty84** [comment]
Hello,

There is a mistake in your script:
```
OPTs=$OPTS" --db_password=password"
```
You wrote `OPTs` instead of `OPTS` (with capital S) :smiley: 

The `--init` does not need to be `all`. You script could be:

```
#! /bin/sh

LOGLEVEL=debug

HOME=/srv/koozic
cd $HOME

OPTS=
OPTS=$OPTS" --pidfile=$HOME/run/koozic.pid"
OPTS=$OPTS" --without-demo=all"
OPTS=$OPTS" --init=oomusic,oovideo"
OPTS=$OPTS" --logfile="$HOME"/logs/koozic.log"
OPTS=$OPTS" --log-level="$LOGLEVEL
OPTS=$OPTS" -d koozic"
OPTS=$OPTS" --db_user=koozic"
OPTS=$OPTS" --db_password=password"
OPTS=$OPTS" --db_host=192.168.207.11"
OPTS=$OPTS" --db_port=5432"
OPTS=$OPTS" --db_sslmode=disable"
OPTS=$OPTS" --db_maxconn=10"
OPTS=$OPTS" --stop-after-init"

cd koozic
exec ./odoo-bin $OPTS
```

By the way, be sure to have this line in your `pg_hba.conf`:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    all             all             0.0.0.0/0               trust
```

Finally, for running, you should make use of:
```
--limit-time-cpu=1800
--limit-time-real=3600
--no-database-list
```

**Comment by mzch** [comment]
Oh, sorry. Thanks for your kind reply!

**Comment by DocMarty84** [comment]
Do not hesitate if you have any other question ;-)
